print("---------Enter five names---------")
a = input("1.")
b = input("2.")
c = input("3.")
d = input("4.")
e = input("5.")
print("")
print("------------Sorted Name------------")
name=[a,b,c,d,e]
newname=sorted(name)
print("1.",newname[0],sep='')
print('2.',newname[1],sep='')
print('3.',newname[2],sep='')
print('4.',newname[3],sep='')
print('5.',newname[4],sep='')
print("-----------------------------------")
input()
