print("Enter 5 names:")
a = input()
b = input()
c = input()
d = input()
e = input()
name=[a,b,c,d,e]
newname=sorted(name)
print("The names are:")
print(newname[0])
print(newname[1])
print(newname[2])
print(newname[3])
print(newname[4])
